const UI_STRINGS = {
  en: {
    backToHome: "← Back to Home",
    libraryTitle: "Case Library",
    librarySubtitle: "Practical decision cases for school principals — drawn from real situations, presented without a single \"correct\" answer.",
    i18nBanner: "Most cases are currently available in Russian and Kazakh — English translations are in progress.",
    filterAll: "All",
    noResults: "No cases match this filter yet.",
    progressLabel: "% completed",
    backToLib: "← Back to Library",
    caseLabel: "Case",
    actionsTitle: "What to do",
    situationSection: "Situation",
    actionsSection: "Director's options",
    conclusionSection: "Conclusion",
    expertLabel: "Commentary",
    accreditationView: "How does this look from an international accreditation perspective?",
    reflectionLabel: "Reflection questions",
    resourcesLabel: "Resources & feedback",
    furtherResources: "Resources for further study",
    shareCTA: "How would you respond?",
    shareText: "Share your approach — the best responses are added to the case analysis once a month.",
    shareButton: "✉ Send your response",
    shareEmailLabel: "or email:",
    openAction: "Open",
    backToActions: "← Back to options",
    next: "Next →",
    viewOptions: "See options →",
    comingSoonTitle: "Coming soon",
    comingSoonText: "This case is being developed. Check back later or explore other available cases.",
    caseNotFound: "Case not found.",
    openMenu: "Open case menu"
  },
  ru: {
    backToHome: "← На главную",
    libraryTitle: "Библиотека кейсов",
    librarySubtitle: "Интерактивный тренажер для директоров школ и всех, кто хочет понять, как устроена школа как организация.",
    libraryPromise: "В основе библиотеки лежит институциональный дизайн школы, то есть система ролей, правил и процессов, которая помогает сохранять знания и устойчиво работать даже при смене людей.",
    jumpToCases: "Перейти к кейсам",
    jumpToHow: "Как пользоваться",
    casesTitle: "Кейсы",
    howTitle: "Как пользоваться кейсами",
    howSummary: "Краткая инструкция",
    howIntro: "Каждый кейс нужно пройти последовательно. Сначала прочитайте ситуацию, затем откройте все варианты и завершите разбор вопросами для своей школы.",
    howStep1Title: "Прочитайте ситуацию",
    howStep1Text: "Отделите факты от предположений и определите, что находится под угрозой.",
    howStep2Title: "Откройте все варианты",
    howStep2Text: "Читайте A, B, C и D по порядку. Они показывают разные управленческие подходы и могут сочетаться в реальной работе.",
    howStep3Title: "Сопоставьте со своей школой",
    howStep3Text: "Используйте авторский разбор и вопросы в конце, чтобы проверить собственные роли, правила и процессы.",
    howNote: "Здесь нет универсально правильного ответа. Более системный вариант тоже может оказаться несвоевременным.",
    aboutTitle: "Об авторе и подходе",
    aboutText: "Меня зовут Дулат Иржанов. Я консультирую частные и общеобразовательные школы. Работал в сельской и городской школах, в системе Назарбаев Интеллектуальных школ и ее центральном аппарате. Участвую в процессах международной аккредитации школ.",
    aboutMethod: "В кейсах я опираюсь на исследования, открытые источники и профессиональный опыт. Разделы об аккредитации передают мое понимание практики и не являются официальными разъяснениями CIS, НИШ или других организаций.",
    subscribeLabel: "Получать письма о новых кейсах:",
    subscribePlaceholder: "Ваш email",
    subscribeButton: "Подписаться",
    subscribeSent: "Вы подписались.",
    i18nBanner: null,
    filterAll: "Все",
    noResults: "По этому фильтру кейсов пока нет.",
    progressLabel: "% пройдено",
    backToLib: "← В библиотеку",
    caseLabel: "Кейс",
    actionsTitle: "Что предпринять",
    situationSection: "Ситуация",
    actionsSection: "Варианты директора",
    conclusionSection: "Итог",
    expertLabel: "Разбор",
    analysisResearchLabel: "Исследования и данные",
    analysisInterpretationLabel: "Авторская интерпретация",
    analysisPracticeLabel: "Из практики",
    analysisApplicationLabel: "Что проверить в своей школе",
    quoteAdaptedLabel: "Из практики. Формулировка адаптирована автором.",
    accreditationView: "Как это выглядит с точки зрения международной аккредитации?",
    reflectionLabel: "Вопросы для размышления",
    resourcesLabel: "Ресурсы и обратная связь",
    furtherResources: "Ресурсы для дальнейшего разбора",
    shareCTA: "Как бы поступили вы?",
    shareText: "Поделитесь своим вариантом, вопросом или предложением. Каждый месяц лучшие ответы и вопросы добавляются в разбор кейсов (анонимно или с авторством на ваш выбор).",
    shareButton: "✉ Отправить свой вариант",
    shareEmailLabel: "или на почту:",
    openAction: "Открыть",
    backToActions: "← Назад к вариантам",
    next: "Далее →",
    viewOptions: "Посмотреть варианты →",
    comingSoonTitle: "Скоро",
    comingSoonText: "Этот кейс в разработке. Загляните позже или откройте другие доступные кейсы.",
    caseNotFound: "Кейс не найден.",
    openMenu: "Открыть меню кейса"
  },
  kk: {
    backToHome: "← Басты бетке",
    libraryTitle: "Кейстер кітапханасы",
    librarySubtitle: "Мектеп директорларына арналған нақты тәжірибеден алынған басқару жағдайлары. Әр кейсте сараптамалық түсіндірме болса да, жалғыз дұрыс жауап осы деп ұсынылмайды.",
    subscribeLabel: "Жаңа кейстер туралы хабар алып тұру үшін жазылыңыз:",
    subscribePlaceholder: "Email мекенжайыңыз",
    subscribeButton: "Жазылу",
    subscribeSent: "Дайын, сіз тізімге қосылдыңыз.",
    i18nBanner: null,
    filterAll: "Барлығы",
    noResults: "Бұл сүзгі бойынша кейстер әлі жоқ.",
    progressLabel: "% өтілді",
    backToLib: "← Кітапханаға",
    caseLabel: "Кейс",
    actionsTitle: "Қандай әрекет жасауға болады",
    situationSection: "Жағдай",
    actionsSection: "Директордың әрекет нұсқалары",
    conclusionSection: "Қорытынды",
    expertLabel: "Сараптамалық түсіндірме",
    accreditationView: "Халықаралық акредиттеу тұрғысынан бұл қалай көрінеді?",
    reflectionLabel: "Ойлануға арналған сұрақтар",
    resourcesLabel: "Ресурстар мен кері байланыс",
    furtherResources: "Тереңірек талдауға арналған дереккөздер",
    shareCTA: "Сіз қалай жасар едіңіз?",
    shareText: "Өз шешіміңізді, сұрағыңызды немесе ұсынысыңызды жіберіңіз. Үздік жауаптар мен сұрақтар ай сайын кейс талдауына қосылады. Автордың аты тек өз келісімімен көрсетіледі.",
    shareButton: "✉ Өз нұсқамды жіберу",
    shareEmailLabel: "немесе поштаға:",
    openAction: "Ашу",
    backToActions: "← Нұсқаларға қайту",
    next: "Келесі →",
    viewOptions: "Нұсқаларды қарау →",
    comingSoonTitle: "Жақында",
    comingSoonText: "Бұл кейс әзірленіп жатыр. Кейінірек қайта кіріңіз немесе қолжетімді басқа кейстерді қараңыз.",
    caseNotFound: "Кейс табылмады.",
    openMenu: "Кейс мәзірін ашу"
  }
};
