const UI_STRINGS = {
  en: {
    backToHome: "← Back to Home",
    libraryTitle: "Case Library",
    librarySubtitle: "Practical decision cases for school principals — drawn from real situations, presented without a single \"correct\" answer.",
    i18nBanner: "Most cases are currently available in Russian and Kazakh — English translations are in progress.",
    filterAll: "All",
    noResults: "No cases match this filter yet.",
    progressLabel: "% completed",
    backToLib: "← Back to Library",
    caseLabel: "Case",
    actionsTitle: "What to do",
    situationSection: "Situation",
    actionsSection: "Director's options",
    conclusionSection: "Conclusion",
    expertLabel: "Commentary",
    accreditationView: "How does this look from an international accreditation perspective?",
    reflectionLabel: "Reflection questions",
    resourcesLabel: "Resources & feedback",
    furtherResources: "Resources for further study",
    shareCTA: "How would you respond?",
    shareText: "Share your approach — the best responses are added to the case analysis once a month.",
    shareButton: "✉ Send your response",
    shareEmailLabel: "or email:",
    openAction: "Open",
    backToActions: "← Back to options",
    next: "Next →",
    viewOptions: "See options →",
    comingSoonTitle: "Coming soon",
    comingSoonText: "This case is being developed. Check back later or explore other available cases.",
    caseNotFound: "Case not found.",
    openMenu: "Open case menu"
  },
  ru: {
    backToHome: "← На главную",
    libraryTitle: "Библиотека кейсов",
    librarySubtitle: "Интерактивный тренажер для директоров школ и всех, кто хочет понять, как устроена школа как организация.",
    libraryPromise: "В основе библиотеки лежит институциональный дизайн школы, то есть система ролей, правил и процессов, которая помогает сохранять знания и устойчиво работать даже при смене людей.",
    jumpToCases: "Перейти к кейсам",
    jumpToHow: "Как пользоваться",
    casesTitle: "Кейсы",
    howTitle: "Как пользоваться кейсами",
    howSummary: "Краткая инструкция",
    howIntro: "Каждый кейс нужно пройти последовательно. Сначала прочитайте ситуацию, затем откройте все варианты и завершите разбор вопросами для своей школы.",
    howStep1Title: "Прочитайте ситуацию",
    howStep1Text: "Отделите факты от предположений и определите, что находится под угрозой.",
    howStep2Title: "Откройте все варианты",
    howStep2Text: "Читайте A, B, C и D по порядку. Они показывают разные управленческие подходы и могут сочетаться в реальной работе.",
    howStep3Title: "Сопоставьте со своей школой",
    howStep3Text: "Используйте авторский разбор и вопросы в конце, чтобы проверить собственные роли, правила и процессы.",
    howNote: "Здесь нет универсально правильного ответа. Более системный вариант тоже может оказаться несвоевременным.",
    aboutTitle: "Об авторе и подходе",
    aboutText: "Меня зовут Дулат Иржанов. Я консультирую частные и общеобразовательные школы. Работал в сельской и городской школах, в системе Назарбаев Интеллектуальных школ и ее центральном аппарате. Участвую в процессах международной аккредитации школ.",
    aboutMethod: "В кейсах я опираюсь на исследования, открытые источники и профессиональный опыт. Разделы об аккредитации передают мое понимание практики. Это не официальные разъяснения CIS, НИШ или других организаций.",
    subscribeLabel: "Получать письма о новых кейсах:",
    subscribeNote: "Новые кейсы появляются по мере готовности. Я использую адрес только для писем об обновлениях.",
    subscribePlaceholder: "Ваш email",
    subscribeButton: "Подписаться",
    subscribeSent: "Вы подписались.",
    i18nBanner: null,
    filterAll: "Все",
    noResults: "По этому фильтру кейсов пока нет.",
    progressLabel: "% пройдено",
    backToLib: "← В библиотеку",
    caseLabel: "Кейс",
    actionsTitle: "Что предпринять",
    actionsGuidanceTitle: "Как читать варианты",
    actionsGuidanceText: "Это не тест. Варианты показывают разные управленческие логики и в реальной работе могут сочетаться. Один подход обычно становится главным из-за ограничений времени, внимания и ресурсов. Более системное решение не всегда подходит для текущего момента.",
    situationSection: "Ситуация",
    actionsSection: "Варианты директора",
    conclusionSection: "Итог",
    expertLabel: "Разбор",
    analysisResearchLabel: "Исследования и данные",
    analysisInterpretationLabel: "Авторская интерпретация",
    analysisPracticeLabel: "Из практики",
    analysisApplicationLabel: "Что проверить в своей школе",
    quoteAdaptedLabel: "Формулировка адаптирована автором по материалам практики.",
    accreditationDisclaimer: "Этот раздел содержит авторское обобщение практики международной аккредитации. Он не воспроизводит официальные материалы и не передает позицию CIS или других организаций.",
    accreditationView: "Как это выглядит с точки зрения международной аккредитации?",
    accreditationSummary: "Авторское обобщение",
    versionLabel: "Версия от",
    reflectionLabel: "Вопросы для размышления",
    resourcesLabel: "Ресурсы и обратная связь",
    furtherResources: "Ресурсы для дальнейшего разбора",
    shareCTA: "Помогите улучшить кейс",
    shareText: "Можно ответить на один или несколько вопросов:",
    shareQuestion1: "Что похоже на вашу практику?",
    shareQuestion2: "Что выглядит неправдоподобно или упрощенно?",
    shareQuestion3: "Какого варианта не хватает?",
    shareQuestion4: "Какой вопрос вы обсудили бы со своей командой?",
    sharePrivacy: "Сообщение не публикуется автоматически. Если я захочу использовать его в кейсе, сначала свяжусь с вами и отдельно согласую анонимность или авторство.",
    shareButton: "✉ Отправить обратную связь",
    shareEmailLabel: "или на почту:",
    openAction: "Открыть",
    backToActions: "← Назад к вариантам",
    next: "Далее →",
    viewOptions: "Посмотреть варианты →",
    comingSoonTitle: "Скоро",
    comingSoonText: "Этот кейс в разработке. Загляните позже или откройте другие доступные кейсы.",
    caseNotFound: "Кейс не найден.",
    openMenu: "Открыть меню кейса"
  },
  kk: {
    backToHome: "← Басты бетке",
    libraryTitle: "Кейстер кітапханасы",
    librarySubtitle: "Мектептің ұйым ретінде қалай жұмыс істейтінін түсінгісі келетін директорлар мен өзге оқырмандарға арналған интерактивті тренажер.",
    libraryPromise: "Кітапхананың өзегінде мектептің институционалдық дизайны тұр. Рөлдер, қағидалар мен процестер білімді сақтап, адамдар ауысқанда да мектептің тұрақты жұмыс істеуіне көмектеседі.",
    jumpToCases: "Кейстерге өту",
    jumpToHow: "Қалай пайдалану керек",
    casesTitle: "Кейстер",
    howTitle: "Кейстерді қалай пайдалану керек",
    howSummary: "Қысқаша нұсқаулық",
    howIntro: "Әр кейсті ретімен өтіңіз. Алдымен жағдайды оқып, кейін барлық нұсқаны ашыңыз. Соңында өз мектебіңізге арналған сұрақтарға жауап беріңіз.",
    howStep1Title: "Жағдайды оқыңыз",
    howStep1Text: "Деректі жорамалдан ажыратып, не нәрсеге қауіп төніп тұрғанын анықтаңыз.",
    howStep2Title: "Барлық нұсқаны ашыңыз",
    howStep2Text: "A, B, C және D нұсқаларын ретімен оқыңыз. Олар басқарудың әртүрлі тәсілдерін көрсетеді және нақты жұмыста қатар қолданылуы мүмкін.",
    howStep3Title: "Өз мектебіңізбен салыстырыңыз",
    howStep3Text: "Авторлық талдау мен соңғы сұрақтар арқылы өз мектебіңіздегі рөлдерді, қағидалар мен процестерді тексеріңіз.",
    howNote: "Барлық жағдайға жарайтын бір дұрыс жауап жоқ. Жүйелі шешімнің өзі дәл осы сәтке сәйкес келмеуі мүмкін.",
    aboutTitle: "Автор және тәсіл туралы",
    aboutText: "Менің атым Дулат Иржанов. Жекеменшік және жалпы білім беретін мектептерге консультация беремін. Ауыл және қала мектептерінде, Назарбаев Зияткерлік мектептері жүйесінде және оның орталық аппаратында жұмыс істедім. Мектептердің халықаралық аккредиттеу процестеріне қатысамын.",
    aboutMethod: "Кейстерді әзірлегенде зерттеулерге, ашық дереккөздерге және кәсіби тәжірибеме сүйенемін. Аккредиттеу туралы бөлімдерде кәсіби пайымымды ұсынамын. Бұл мәтіндер CIS, НЗМ немесе басқа ұйымдардың ресми түсіндірмесі емес.",
    subscribeLabel: "Жаңа кейстер туралы хабар алу үшін жазылыңыз:",
    subscribeNote: "Жаңа кейстер дайын болуына қарай жарияланады. Email мекенжайын жаңартулар туралы хаттар үшін ғана пайдаланамын.",
    subscribePlaceholder: "Email мекенжайыңыз",
    subscribeButton: "Жазылу",
    subscribeSent: "Сіз жазылдыңыз.",
    i18nBanner: null,
    filterAll: "Барлығы",
    noResults: "Бұл сүзгі бойынша кейстер әлі жоқ.",
    progressLabel: "% өтілді",
    backToLib: "← Кітапханаға",
    caseLabel: "Кейс",
    actionsTitle: "Қандай әрекет жасауға болады",
    actionsGuidanceTitle: "Нұсқаларды қалай оқу керек",
    actionsGuidanceText: "Бұл тест емес. Нұсқалар басқарудың әртүрлі логикасын көрсетеді және нақты жұмыста қатар қолданылуы мүмкін. Уақыт, назар және ресурс шектеулі болғандықтан, бір тәсіл негізгі орын алады. Жүйелі шешімнің өзі дәл осы сәтке сәйкес келмеуі мүмкін.",
    situationSection: "Жағдай",
    actionsSection: "Директордың әрекет нұсқалары",
    conclusionSection: "Қорытынды",
    expertLabel: "Талдау",
    analysisResearchLabel: "Зерттеулер мен деректер",
    analysisInterpretationLabel: "Авторлық пайым",
    analysisPracticeLabel: "Тәжірибеден",
    analysisApplicationLabel: "Өз мектебіңізде нені тексеру керек",
    quoteAdaptedLabel: "Автор тәжірибе материалдары негізінде бейімдеген тұжырым.",
    accreditationDisclaimer: "Бұл бөлім халықаралық аккредиттеу тәжірибесін авторлық тұрғыдан жинақтайды. Онда ресми материалдар көшірілмейді және CIS пен басқа ұйымдардың ұстанымы берілмейді.",
    accreditationView: "Халықаралық аккредиттеу тұрғысынан бұл қалай көрінеді?",
    accreditationSummary: "Авторлық түсіндірме",
    versionLabel: "Нұсқа күні",
    reflectionLabel: "Ойлануға арналған сұрақтар",
    resourcesLabel: "Ресурстар мен кері байланыс",
    furtherResources: "Тереңірек талдауға арналған дереккөздер",
    shareCTA: "Кейсті жақсартуға көмектесіңіз",
    shareText: "Бір немесе бірнеше сұраққа жауап беруге болады.",
    shareQuestion1: "Сіздің тәжірибеңізге не ұқсайды?",
    shareQuestion2: "Қай тұсы шындыққа жанаспайды немесе тым жеңілдетілген?",
    shareQuestion3: "Қандай нұсқа жетіспейді?",
    shareQuestion4: "Командаңызбен қай сұрақты талқылар едіңіз?",
    sharePrivacy: "Хабарлама автоматты түрде жарияланбайды. Оны кейсте пайдаланғым келсе, алдымен сізбен хабарласып, анонимдік немесе авторлық туралы бөлек келісемін.",
    shareButton: "✉ Кері байланыс жіберу",
    shareEmailLabel: "немесе поштаға:",
    openAction: "Ашу",
    backToActions: "← Нұсқаларға қайту",
    next: "Келесі →",
    viewOptions: "Нұсқаларды қарау →",
    comingSoonTitle: "Жақында",
    comingSoonText: "Бұл кейс әзірленіп жатыр. Кейінірек қайта кіріңіз немесе қолжетімді басқа кейстерді қараңыз.",
    caseNotFound: "Кейс табылмады.",
    openMenu: "Кейс мәзірін ашу"
  }
};
