const UI_STRINGS = {
  en: {
    backToHome: "← Back to Home",
    libraryTitle: "Case Library",
    librarySubtitle: "Practical decision cases for school principals — drawn from real situations, presented without a single \"correct\" answer.",
    i18nBanner: "Most cases are currently available in Russian and Kazakh — English translations are in progress.",
    filterAll: "All",
    noResults: "No cases match this filter yet.",
    progressLabel: "% completed",
    backToLib: "← Back to Library",
    caseLabel: "Case",
    actionsTitle: "What to do",
    situationSection: "Situation",
    actionsSection: "Director's options",
    conclusionSection: "Conclusion",
    expertLabel: "Commentary",
    reflectionLabel: "Reflection questions",
    resourcesLabel: "Resources & feedback",
    furtherResources: "Resources for further study",
    shareCTA: "How would you respond?",
    shareText: "Share your approach — the best responses are added to the case analysis once a month.",
    shareButton: "✉ Send your response",
    shareEmailLabel: "or email:",
    openAction: "Open",
    backToActions: "← Back to options",
    next: "Next →",
    viewOptions: "See options →",
    comingSoonTitle: "Coming soon",
    comingSoonText: "This case is being developed. Check back later or explore other available cases."
  },
  ru: {
    backToHome: "← На главную",
    libraryTitle: "Библиотека кейсов",
    librarySubtitle: "Учебные управленческие ситуации для директоров школ — из реальной практики, без единственно верного ответа.",
    i18nBanner: null,
    filterAll: "Все",
    noResults: "По этому фильтру кейсов пока нет.",
    progressLabel: "% пройдено",
    backToLib: "← В библиотеку",
    caseLabel: "Кейс",
    actionsTitle: "Что предпринять",
    situationSection: "Ситуация",
    actionsSection: "Варианты директора",
    conclusionSection: "Итог",
    expertLabel: "Комментарий",
    reflectionLabel: "Вопросы для размышления",
    resourcesLabel: "Ресурсы и обратная связь",
    furtherResources: "Ресурсы для дальнейшего разбора",
    shareCTA: "Как бы поступили вы?",
    shareText: "Поделитесь своим вариантом — раз в месяц лучшие ответы добавляются в разбор кейса.",
    shareButton: "✉ Отправить свой вариант",
    shareEmailLabel: "или на почту:",
    openAction: "Открыть",
    backToActions: "← Назад к вариантам",
    next: "Далее →",
    viewOptions: "Посмотреть варианты →",
    comingSoonTitle: "Скоро",
    comingSoonText: "Этот кейс в разработке. Загляните позже или откройте другие доступные кейсы."
  },
  kk: {
    backToHome: "← Басты бетке",
    libraryTitle: "Кейс кітапханасы",
    librarySubtitle: "Мектеп директорларына арналған басқару жағдаяттары — нақты тәжірибеден, жалғыз дұрыс жауапсыз.",
    i18nBanner: null,
    filterAll: "Барлығы",
    noResults: "Бұл сүзгі бойынша кейстер әлі жоқ.",
    progressLabel: "% өтілді",
    backToLib: "← Кітапханаға",
    caseLabel: "Кейс",
    actionsTitle: "Не істеу керек",
    situationSection: "Жағдай",
    actionsSection: "Директордың нұсқалары",
    conclusionSection: "Қорытынды",
    expertLabel: "Пікір",
    reflectionLabel: "Ойлануға арналған сұрақтар",
    resourcesLabel: "Ресурстар мен кері байланыс",
    furtherResources: "Одан әрі зерттеуге арналған ресурстар",
    shareCTA: "Сіз қалай жасар едіңіз?",
    shareText: "Өз нұсқаңызбен бөлісіңіз — ең жақсы жауаптар айына бір рет кейс талдауына қосылады.",
    shareButton: "✉ Өз нұсқамды жіберу",
    shareEmailLabel: "немесе поштаға:",
    openAction: "Ашу",
    backToActions: "← Нұсқаларға қайту",
    next: "Келесі →",
    viewOptions: "Нұсқаларды қарау →",
    comingSoonTitle: "Жақында",
    comingSoonText: "Бұл кейс әзірленуде. Кейінірек кіріңіз немесе басқа қол жетімді кейстерді ашыңыз."
  }
};
