(function () {
  window.AUDIT_COPY = {
    ru: {
      title: "Экспресс-аудит школы", eyebrow: "Практический инструмент · Первый разговор",
      lede: "За десять минут соберите факты, которые помогут содержательно обсудить ситуацию школы и определить следующий шаг.",
      privacy: "Сайт не сохраняет и не отправляет ответы автоматически. До выбора способа отправки данные остаются в этой вкладке и исчезают после обновления страницы.",
      metrics: [["14 вопросов","Точные цифры не требуются"],["Около 10 минут","Можно отвечать кратко"],["Ваш результат","Печать, PDF или email"]],
      sections: [["О школе","Основные факты и организационный контекст."],["Команда","Руководство, распределение ответственности и рабочие системы."],["Повод обращения и горизонт","Задача, предыдущие действия и срок решения."]],
      questions: [
        ["Название школы и город","text",""],["Тип школы","area","Частная, государственная, сетевая, международная франшиза или другое"],
        ["Год основания и примерное количество учеников тогда и сейчас. Как менялась численность?","area",""],["Программа обучения","text","Национальная, IB, Cambridge, смешанная или другая"],
        ["Государственная лицензия или аккредитация. Есть ли международная аккредитация или членство?","area",""],["Кто является учредителем или владельцем школы?","area",""],
        ["Имя директора и сколько лет он или она работает на этой должности","text",""],["Кому подчиняется директор и насколько активно эта инстанция участвует в решениях?","area",""],
        ["Кто входит в ключевую руководящую команду? Стабилен ли ее состав последние два года?","area",""],["Кто отвечает за IT и какие системы школа использует для управления?","area","Учет учеников и оценок, финансы, Excel, WhatsApp или другие инструменты"],
        ["Кто заполняет эту анкету?","text","Имя и роль"],["Что стало поводом обратиться сейчас? Как вы формулируете запрос и что уже пробовали?","long",""],
        ["Какие крупные вызовы или планы вы видите на горизонте двух-пяти лет? Они закреплены в документе или пока обсуждаются?","long",""],["Есть ли срок, к которому нужно определиться?","text",""]
      ],
      complete:"Завершение", filled:n=>`Заполнено ${n} из 14 вопросов.`, selfEmail:"Email для отправки себе", print:"Распечатать или сохранить PDF", printBlank:"Распечатать пустую форму", sendAuthor:"Отправить Дулату", sendSelf:"Отправить себе", clear:"Очистить", emailNote:"При отправке откроется ваша почтовая программа. Если текст окажется слишком длинным для письма, ответы будут скопированы в буфер обмена.",
      confirmClear:"Очистить все ответы? Восстановить их после этого будет невозможно.", invalidEmail:"Введите корректный адрес электронной почты.", copied:"Ответы скопированы. Вставьте их в письмо после открытия почтовой программы.", tooLong:"Текст слишком длинный для автоматической вставки. Сначала сохраните аудит в PDF, затем приложите файл к письму.",
      reportSubtitle:"Материалы для подготовки консультации", school:"Школа", preparedBy:"Подготовил(а)", notGiven:"Ответ не указан", notice:"Документ составлен по сведениям, предоставленным представителем школы. Он служит основой для первого разговора и не является заключением о качестве работы школы.", profile:"Профиль школы", managementRequest:"Основной управленческий запрос", deadline:"Срок решения", leadership:"Руководство и рабочие системы", horizon:"Горизонт развития", blankSubtitle:"Форма для заполнения от руки", blankInstruction:"Пишите кратко. Если места недостаточно, продолжите ответ на отдельном листе.", emailSubject:"Экспресс-аудит школы", source:"Источник формы: dulatedu.com/tools/"
    },
    kk: {
      title: "Мектептің экспресс-аудиті", eyebrow: "Практикалық құрал · Алғашқы әңгіме",
      lede: "Он минут ішінде мектептің жағдайын мазмұнды талқылауға және келесі қадамды анықтауға қажетті деректерді жинаңыз.",
      privacy: "Сайт жауаптарды сақтамайды және автоматты түрде жібермейді. Жіберу тәсілін таңдағанға дейін деректер осы бетте ғана қалады және бет жаңартылғанда өшеді.",
      metrics: [["14 сұрақ","Нақты сандар міндетті емес"],["Шамамен 10 минут","Қысқа жауап беруге болады"],["Нәтиже","Басып шығару, PDF немесе email"]],
      sections: [["Мектеп туралы","Негізгі деректер мен ұйымдық жағдай."],["Команда","Басшылық, жауапкершіліктің бөлінуі және жұмыс жүйелері."],["Өтініштің себебі мен мерзімі","Мәселе, бұған дейінгі әрекеттер және шешім қабылдау мерзімі."]],
      questions: [
        ["Мектептің атауы және орналасқан қаласы","text",""],["Мектептің түрі","area","Жекеменшік, мемлекеттік, желілік, халықаралық франшиза немесе басқа"],
        ["Мектептің құрылған жылы және сол кездегі әрі қазіргі оқушы саны. Оқушы саны қалай өзгерді?","area",""],["Оқу бағдарламасы","text","Ұлттық, IB, Cambridge, аралас немесе басқа бағдарлама"],
        ["Мемлекеттік лицензиясы немесе аккредиттеуі қандай? Халықаралық аккредиттеуі немесе мүшелігі бар ма?","area",""],["Мектептің құрылтайшысы немесе иесі кім?","area",""],
        ["Директордың аты-жөні және осы қызметтегі еңбек өтілі","text",""],["Директор кімге есеп береді және бұл орган шешім қабылдауға қаншалықты белсенді қатысады?","area",""],
        ["Негізгі басқарушы командаға кімдер кіреді? Соңғы екі жылда оның құрамы тұрақты болды ма?","area",""],["IT бағытына кім жауап береді және мектепті басқару үшін қандай жүйелер қолданылады?","area","Оқушылар мен бағаларды есепке алу, қаржы, Excel, WhatsApp немесе басқа құралдар"],
        ["Бұл сауалнаманы кім толтырып отыр?","text","Аты-жөні және қызметі"],["Дәл қазір кеңес алуға не себеп болды? Сұранысыңызды қалай тұжырымдайсыз және бұған дейін не істеп көрдіңіз?","long",""],
        ["Алдағы екі-бес жылда қандай ірі міндеттер немесе жоспарлар бар? Олар құжатта бекітілген бе, әлде әзірге ауызша талқыланып жүр ме?","long",""],["Қай мерзімге дейін шешім қабылдау қажет?","text",""]
      ],
      complete:"Аяқтау", filled:n=>`${n}/14 сұрақ толтырылды.`, selfEmail:"Өзіңізге жіберетін email", print:"Басып шығару немесе PDF сақтау", printBlank:"Бос нысанды басып шығару", sendAuthor:"Дулатқа жіберу", sendSelf:"Өзіме жіберу", clear:"Тазарту", emailNote:"Жіберу кезінде пошта бағдарламасы ашылады. Мәтін хат үшін тым ұзын болса, жауаптар алмасу буферіне көшіріледі.",
      confirmClear:"Барлық жауап өшірілсін бе? Оларды кейін қалпына келтіру мүмкін болмайды.", invalidEmail:"Дұрыс электрондық пошта мекенжайын енгізіңіз.", copied:"Жауаптар көшірілді. Пошта бағдарламасы ашылғаннан кейін оларды хатқа қойыңыз.", tooLong:"Мәтін автоматты түрде енгізу үшін тым ұзын. Аудитті алдымен PDF түрінде сақтап, файлды хатқа тіркеңіз.",
      reportSubtitle:"Кеңеске дайындалуға арналған материалдар", school:"Мектеп", preparedBy:"Толтырған адам", notGiven:"Жауап берілмеген", notice:"Құжат мектеп өкілі ұсынған мәліметтер негізінде жасалды. Ол алғашқы әңгімеге дайындалуға арналған және мектеп жұмысының сапасы туралы қорытынды болып саналмайды.", profile:"Мектеп туралы мәлімет", managementRequest:"Негізгі басқарушылық сұраныс", deadline:"Шешім қабылдау мерзімі", leadership:"Басшылық және жұмыс жүйелері", horizon:"Даму көкжиегі", blankSubtitle:"Қолмен толтыруға арналған нысан", blankInstruction:"Қысқа жазыңыз. Орын жетпесе, жауапты бөлек парақта жалғастырыңыз.", emailSubject:"Мектептің экспресс-аудиті", source:"Нысан көзі: dulatedu.com/tools/"
    },
    en: {
      title:"School Express Audit", eyebrow:"Practical tool · Initial conversation", lede:"In ten minutes, gather the facts needed for a focused conversation about the school and its next step.", privacy:"The website does not store or automatically send your answers. Until you choose how to send them, the data remains in this tab and disappears when the page is refreshed.",
      metrics:[["14 questions","Exact figures are not required"],["About 10 minutes","Brief answers are sufficient"],["Your result","Print, PDF, or email"]], sections:[["About the school","Essential facts and organisational context."],["Leadership team","Leadership, accountability, and operating systems."],["Reason for contacting us and timeframe","The challenge, previous actions, and decision deadline."]],
      questions:[["School name and city","text",""],["Type of school","area","Private, public, network school, international franchise, or other"],["Year founded and approximate enrolment then and now. How has enrolment changed?","area",""],["Curriculum","text","National, IB, Cambridge, blended, or other"],["Government licence or accreditation. Does the school also hold international accreditation or membership?","area",""],["Who founded or owns the school?","area",""],["Principal's name and number of years in the role","text",""],["To whom is the principal accountable, and how actively does that person or body participate in decisions?","area",""],["Who is on the senior leadership team? Has the team been stable over the past two years?","area",""],["Who is responsible for IT, and which systems does the school use for management?","area","Student records and grades, finance, Excel, WhatsApp, or other tools"],["Who is completing this questionnaire?","text","Name and role"],["What prompted you to seek advice now? How would you describe the challenge, and what have you already tried?","long",""],["What major challenges or plans do you see over the next two to five years? Are they documented or still discussed informally?","long",""],["Is there a deadline by which a decision must be made?","text",""]],
      complete:"Finish", filled:n=>`${n} of 14 questions completed.`, selfEmail:"Email for sending yourself a copy", print:"Print or save as PDF", printBlank:"Print a blank form", sendAuthor:"Send to Dulat", sendSelf:"Send to myself", clear:"Clear", emailNote:"Your email application will open when you send the form. If the text is too long for an email link, the answers will be copied to your clipboard.", confirmClear:"Clear all answers? They cannot be recovered afterwards.", invalidEmail:"Enter a valid email address.", copied:"The answers have been copied. Paste them into the message after your email application opens.", tooLong:"The text is too long to insert automatically. Save the audit as a PDF first, then attach it to your email.", reportSubtitle:"Materials for consultation preparation", school:"School", preparedBy:"Prepared by", notGiven:"No answer provided", notice:"This document is based on information supplied by a representative of the school. It supports an initial conversation and is not an evaluation of the quality of the school.", profile:"School profile", managementRequest:"Primary management challenge", deadline:"Decision deadline", leadership:"Leadership and operating systems", horizon:"Development horizon", blankSubtitle:"Form for handwritten completion", blankInstruction:"Keep your answers brief. If you need more space, continue on a separate sheet.", emailSubject:"School Express Audit", source:"Form source: dulatedu.com/tools/"
    }
  };
})();
